### ISSUE TITLE
Unable to run vizceral-example

### ISSUE THREAD

**Issue by mantikhoras** [Netflix/vizceral-example#23]
Justin,

I am attempting to run vizceral/example within an Ubuntu 14.04 VM
and have followed setup steps outlined here :

https://github.com/Netflix/vizceral
https://github.com/Netflix/vizceral-example

Accessing localhost:8080, however, results in the following errors :

[568] ./src/components/updateStatus.css 940 bytes {0} [built] [1 error]

ERROR in ./~/css-loader!./src/app.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/app.css 4:14-74

ERROR in ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./~/bootstrap/dist/css/bootstrap.css 4:14-73

ERROR in ./~/css-loader!./src/components/trafficFlow.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/components/trafficFlow.css 4:14-85

ERROR in ./~/css-loader!./~/vizceral-react/dist/vizceral.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./~/vizceral-react/dist/vizceral.css 4:14-69

ERROR in ./~/css-loader!./src/components/breadcrumbs.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/components/breadcrumbs.css 4:14-85

ERROR in ./~/css-loader!./src/components/physicsOptions.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/components/physicsOptions.css 4:14-88

ERROR in ./~/css-loader!./src/components/controls.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/components/controls.css 4:14-82

ERROR in ./~/css-loader!./src/components/detailsPanel.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/components/detailsPanel.css 4:14-86

ERROR in ./~/css-loader!./src/components/loadingCover.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/components/loadingCover.css 4:14-86

ERROR in ./~/css-loader!./src/components/locator.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/components/locator.css 4:14-81

ERROR in ./~/css-loader!./src/components/optionsPanel.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/components/optionsPanel.css 4:14-86

ERROR in ./~/css-loader!./src/components/updateStatus.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/components/updateStatus.css 4:14-86

ERROR in ./~/css-loader!./~/react-virtualized/styles.css
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:227:31)
    at LazyResult.then (/home/user/Vizceral-Example/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:131:21)
    at processCss (/home/user/Vizceral-Example/node_modules/css-loader/lib/processCss.js:200:5)
    at Object.module.exports (/home/user/Vizceral-Example/node_modules/css-loader/lib/loader.js:24:2)
 @ ./~/react-virtualized/styles.css 4:14-64
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 1.49 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 1.49 kB {0} [built]
webpack: bundle is now VALID.

Not entirely sure if this is applicable (I'm rather new to the realm of NodeJS), but :

user@user-VirtualBox:~/Vizceral$ npm version
{ vizceral: '4.3.0',
  npm: '3.3.6',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '56.1',
  modules: '47',
  node: '5.0.0',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.6.85.28',
  zlib: '1.2.8' }

user@user-VirtualBox:~/Vizceral$ nvm ls
         v4.0.0
->       v5.0.0
         system

Please advise.

**Comment by jrsquared** [comment]
Accessing localhost:8080 results in those errors? Those look like webpack build errors that should happen when running `npm run dev`...

I ran a clean clone/install using the same version of node and npm and did not get the same errors.

One thing I did notice that was odd is that npm version is showing `vizceral` instaed of `vizceral-example`.  When trying to use vizceral-example, you don't have to do anything with the `vizceral` repository, it gets installed automatically as a dependency.

Maybe try again fresh with only vizceral-example?

**Comment by shadfx** [comment]
based on the https://webkul.com/blog/use-webpack-prestashop-1-7-classic-theme/ link 
I did the below to fix the issue

npm install es6-promise --save
and then added require(‘es6-promise’).polyfill() at the top of webpack.config.js.

**Comment by jrsquared** [comment]
Glad you were able to figure it out! Which browser and version are you trying to use?

**Comment by mantikhoras** [comment]
Thank you, Justin. 

This ended up being a simple mismatch on my part. I'll close the issue.
